name: adbready
description: Android ADB ready for Flutter
version: 1.0.0
homepage: https://github.com/olankens/adbready

environment:
  sdk: '>=2.18.4 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.example.adbready
        pluginClass: AdbreadyPlugin
